### DISCUSSION TITLE
Why don't I see any logs?

### DISCUSSION THREAD

**Discussion by NadChel** [qos-ch/slf4j#349] [Q&A] [answered]
I am new to SLF4J. I tried to "separate my concerns" and make this library do the logging in my app (which did the logging on its own). Here's what I tried
```java
@Slf4j
public class Measurer {
// ...
log.info(averageMeasurementLog(measuredProcedure));
// ...
private String averageMeasurementLog(MeasuredProcedure measuredProcedure) {
// builds and returns a String
```
`log4j2.yml` in the resources root:
```yml
Configuration:
  thresholdFilter:
    level: info
  appenders:
    Console:
      name: CONSOLE
      PatternLayout:
        pattern: "%m"
      target: SYSTEM_OUT
    File:
      name: FILE
      fileName: "log.txt"
  Loggers:
    Root:
      level: info
      AppenderRef:
         ref: CONSOLE
```
`pom.xml`:
```xml
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.7</version>
    </dependency>

    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j2-impl</artifactId>
      <version>2.20.0</version>
    </dependency>
```
Unfortunately, I don't see anything in my console output. Why is that?
